export const POLL_CREATE_RESET = 'POLL_CREATE_RESET';
export const POLL_CREATE_SET_CREATED = 'POLL_CREATE_SET_CREATED';
export const POLL_CREATE_SET_ERROR = 'POLL_CREATE_SET_ERROR';
export const POLL_CREATE_SET_VIOLATIONS = 'POLL_CREATE_SET_VIOLATIONS';
export const POLL_CREATE_TOGGLE_LOADING = 'POLL_CREATE_TOGGLE_LOADING';
