export const POLL_SHOW_RESET = 'POLL_SHOW_RESET';
export const POLL_SHOW_SET_ERROR = 'POLL_SHOW_SET_ERROR';
export const POLL_SHOW_SET_RETRIEVED = 'POLL_SHOW_SET_RETRIEVED';
export const POLL_SHOW_TOGGLE_LOADING = 'POLL_SHOW_TOGGLE_LOADING';
