export const RESET = 'VOTE_UPDATE_RESET';
export const SET_ERROR = 'VOTE_UPDATE_SET_ERROR';
export const SET_RETRIEVED = 'VOTE_UPDATE_SET_RETRIEVED';
export const SET_UPDATED = 'VOTE_UPDATE_SET_UPDATED';
export const SET_VIOLATIONS = 'VOTE_UPDATE_SET_VIOLATIONS';
export const TOGGLE_LOADING = 'VOTE_UPDATE_TOGGLE_LOADING';
