export const TRACK_SHOW_RESET = 'TRACK_SHOW_RESET';
export const TRACK_SHOW_SET_ERROR = 'TRACK_SHOW_SET_ERROR';
export const TRACK_SHOW_SET_RETRIEVED = 'TRACK_SHOW_SET_RETRIEVED';
export const TRACK_SHOW_TOGGLE_LOADING = 'TRACK_SHOW_TOGGLE_LOADING';
