export const VOTE_DELETE_RESET = 'VOTE_DELETE_RESET';
export const VOTE_DELETE_SET_ERROR = 'VOTE_DELETE_SET_ERROR';
export const VOTE_DELETE_SET_DELETED = 'VOTE_DELETE_SET_DELETED';
export const VOTE_DELETE_TOGGLE_LOADING = 'VOTE_DELETE_TOGGLE_LOADING';
