export const POLL_DELETE_RESET = 'POLL_DELETE_RESET';
export const POLL_DELETE_SET_ERROR = 'POLL_DELETE_SET_ERROR';
export const POLL_DELETE_SET_DELETED = 'POLL_DELETE_SET_DELETED';
export const POLL_DELETE_TOGGLE_LOADING = 'POLL_DELETE_TOGGLE_LOADING';
