export const VOTE_SHOW_RESET = 'VOTE_SHOW_RESET';
export const VOTE_SHOW_SET_ERROR = 'VOTE_SHOW_SET_ERROR';
export const VOTE_SHOW_SET_RETRIEVED = 'VOTE_SHOW_SET_RETRIEVED';
export const VOTE_SHOW_TOGGLE_LOADING = 'VOTE_SHOW_TOGGLE_LOADING';
